# Placeholder docker-compose.yml for API, Qdrant, and Prometheus 

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - API_TOKEN=${API_TOKEN}
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - MONGODB_URI=mongodb://mongodb:27017
      - LANGCHAIN_TRACING_V2=true
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
    depends_on:
      - qdrant
      - mongodb
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  ui:
    build: ../ui
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      - API_URL=http://api:8000
      - API_TOKEN=${API_TOKEN}
      - LANGCHAIN_TRACING_V2=true
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
    depends_on:
      - api

volumes:
  mongo_data: 